name: Test two actions
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action1
      - uses: ./action2
